name: 'Generate GitHub Token'
description: 'Generates a GitHub token using a private key, app ID, and installation ID'

inputs:
  private_key:
    description: 'The private key content'
    required: true

outputs:
  github_token:
    description: 'Generated GitHub token'

runs:
  using: 'composite'
  steps:
    - name: Export private key
      shell: bash
      run: echo "${{ inputs.private_key }}" > key.pem

    - name: Execute Python script
      shell: bash
      id: generate_token
      run: |
        TOKEN=$(python gh_token/script.py key.pem 903110 50999118)
        echo "GITHUB_TOKEN=$TOKEN" >> $GITHUB_ENV
        echo "::set-output name=github_token::$TOKEN"
