name: Fetch Archived Repos

on:
  workflow_dispatch:
    inputs:
      organization_name:
        description: 'Organization Name'
        required: true

env: 
  github_token: ${{ secrets.GITHUB_TOKEN }}

jobs:
  fetch_repos:
  runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Fetch Archived Repos
        run: |
          python archive.py ${{ secrets.GITHUB_TOKEN }} ${{ github.event.inputs.organization_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}

      - name: Export Archive Excel file
        uses: actions/upload-artifact@v2
        with:
          name: excel-artifact
          path: pwc-gx-ifs-ngc_archived_repos.xlsx