name: Publish Docker Image
on:
  push:
    # tags:
    #   - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get latest tag
        id: get_tag
        run: echo "::set-output name=TAG::$(git describe --tags --abbrev=0)"

      - name: Get commit count
        id: get_commit_count
        run: echo "::set-output name=COMMIT_COUNT::$(git rev-list ${GITHUB_SHA} --count)"

      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker buildx create --use
          docker buildx build --push \
            --tag shubhamtyagiio/poc:${{ steps.get_tag.output.TAG }} \
            --tag shubhamtyagiio/poc:latest \
            --build-arg COMMIT_COUNT=${{ steps.get_commit_count.output.COMMIT_COUNT }} \
            --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
            .

          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push shubhamtyagiio/poc:${{ steps.get_tag.output.TAG }}
          docker push shubhamtyagiio/poc:latest
