name: Example Workflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Generate GitHub Token
        id: generate_token
        uses: ./gh_token
        with:
          private_key: ${{ secrets.PRIV_KEY }}
          app_id: 903110
          installation_id: 50999118
          
      - name: Use GitHub Token
        run: |
          echo "GitHub Token: ${{ steps.generate_token.outputs.github_token }}"
