name: Example Workflow
on: [push]

jobs:
  token:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use GitHub path
        run: |
          echo "Workspace directory: $GITHUB_WORKSPACE"
          echo "Repository root: $GITHUB_REPOSITORY"
      
      - name: Generate GitHub Token
        id: generate_token
        uses: ./gh_token
        with:
          private_key: ${{ secrets.PRIV_KEY }}
          app_id: '903110'
          installation_id: '50999118'
          
      - name: Store GitHub Token as Secret
        run: |
          echo "GHS_TOKEN=${{ steps.generate_token.outputs.token }}" >> $GITHUB_ENV
          echo "GHS_TOKEN=${{ env.GHS_TOKEN }}"
