---
name: Sample Workflow
on: [push]

jobs:
  token:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use GitHub path
        run: |
          echo "Workspace directory: $GITHUB_WORKSPACE"
          echo "Repository root: $GITHUB_REPOSITORY"
      
      - name: Generate GitHub Token
        id: generate_token
        uses: ./gh_token
        with:
          private_key: "${{ secrets.PRIV_KEY }}"

      - name: export token
        shell: bash
        run: |
          cat token.txt
          export GHA_TOKEN=$(cat token.txt)

      # - name: echo token
      #    shell: bash
      #    run: |
      #      echo $GHA_TOKEN
          
      # - name: Store GitHub Token as Secret
      #   run: |
      #     echo "GHS_TOKEN=${{ steps.generate_token.outputs.github_token }}" >> $GITHUB_ENV
      #     echo "GHS_TOKEN=${{ env.GHS_TOKEN }}"
