---
name: Sample Workflow
on: [push]

jobs:
  validation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Generate GitHub Token
        id: generate_token
        uses: ./gh_token
        with:
          private_key: "${{ secrets.PRIV_KEY }}"

      - name: trigger python automation scripts
        shell: bash
        run: |
          export GHA_TOKEN=$(cat token.txt)
          python gh_token/test.py $GHA_TOKEN shubham-tyagi-io

  user_automation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate GitHub Token
        id: generate_token
        uses: ./gh_token
        with:
          private_key: "${{ secrets.PRIV_KEY }}"

      - name: trigger python automation scripts
        shell: bash
        run: |
          export GHA_TOKEN=$(cat token.txt)
          python gh_token/test.py $GHA_TOKEN shubham-tyagi-io