name: Workflow test

on:
  workflow_dispatch:
    inputs:
      organization_name:
        description: 'Organization Name'
        required: true
        default: "["abc-dog-pc", "pqr-str", "prt-jg"]"

      archive_repo:
        description: "repository archival"
        type: boolean
        default: false

jobs:
  fetch_repos:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        print: ${{ github.event.inputs.organization_name }}
    steps:
      - name: echo
        run: |
          echo ${{ matrix.print }}
