name: Workflow test

on:
  workflow_dispatch:
    inputs:
      organization_name:
        description: 'Organization Name'
        required: true
        default: "abc, pqr, xyz"

jobs:
  envPrepare:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: prepare repo names to list
        id: step1
        run: |
          echo "::set-output name=repo_name::$(echo ${{ github.event.inputs.organization_name }} | tr ',' '\n')"
    outputs:
      archive_result: ${{ env.archive_result }}
      repo_name: ${{ steps.step1.outputs.repo_name }}

  fetch_repos:
    runs-on: ubuntu-latest
    needs: [envPrepare]
    strategy:
      matrix:
        print: ${{fromJson(needs.envPrepare.outputs.repo_name)}}
    steps:
      - name: echo
        run: |
          echo ${{ matrix.print }}
